steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/river-oxygen-369017/cedille', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/river-oxygen-369017/cedille']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cedille', '--image', 'gcr.io/river-oxygen-369017/cedille', '--region', 'us-central1']
images:
- gcr.io/river-oxygen-369017/cedille
